=== abuishak/info2351/tvlist.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tvlist ( cd, title, programe*, chanal*, name, time, month,year, news, search*) >
<!ELEMENT cd (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT programe (#PCDATA) >
<!ELEMENT chanal (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT time (#PCDATA) >
<!ELEMENT month (#PCDATA) >
<!ELEMENT year (#PCDATA) >
<!ELEMENT news (#PCDATA) >
<!ELEMENT search (#PCDATA) >

=== abuishak/info2351/week4tvlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tvlist SYSTEM "tvlist.dtd">
<tvlist>
    <cd></cd>
    <title>Tv Listings</title>
    <programe>Movie</programe>
    <chanal>CBS</chanal>
    <name>Darken Dill</name>
    <time>10:30PM</time>
    <month>june</month>
    <year>2017</year>
    <news>English AT: 10:00 PM</news>
    <search>Listing</search>
    
</tvlist>
